project_id = "xsknebhsscviwkvjdgux"

[functions.deep-research]
verify_jwt = false

[functions.subject-summary]
verify_jwt = false


[functions.records-proxy]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.fetch-gdelt-news]
verify_jwt = false

[functions.cms-api]
verify_jwt = false

[functions.check-link-health]
verify_jwt = false
